openapi: 3.2.0
info:
  title: Authelia Password Change API
  description: Authelia is an open-source authentication and authorization server and portal fulfilling the identity and access management (IAM) role of information security in providing multi-factor authentication and single sign-on (SSO) for your applications via a web portal. Authelia is an OpenID Connect 1.0 Provider which is OpenID Certified™ allowing comprehensive integrations, and acts as a companion for common reverse proxies.
  contact:
    name: Support
    url: https://www.authelia.com/contact/
    email: team@authelia.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
servers:
- url: https://auth.example.com
  description: Authelia API
tags:
- name: Password Change
  description: Password change endpoint
paths:
  /api/change-password:
    post:
      operationId: postChangePassword
      tags:
      - Password Change
      summary: Password Change
      description: The password change endpoint validates the user session, validates, and changes the password. The same session cookie must be used for all steps in this process.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/handlers.PasswordChangeRequestBody'
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/middlewares.Response.OK'
      security:
      - authelia_auth: []
components:
  schemas:
    middlewares.Response.OK:
      type: object
      required:
      - status
      properties:
        status:
          enum:
          - OK
          type: string
          examples:
          - OK
        data:
          type: object
          description: The data content for the response.
    handlers.PasswordChangeRequestBody:
      required:
      - username
      - old_password
      - new_password
      type: object
      properties:
        username:
          type: string
          examples:
          - john
        old_password:
          type: string
          examples:
          - old_password123
        new_password:
          type: string
          examples:
          - new_password456
  securitySchemes:
    authelia_auth:
      type: apiKey
      name: authelia_session
      in: cookie
    openid:
      type: openIdConnect
      openIdConnectUrl: https://auth.example.com/.well-known/openid-configuration
